data:
  img_size: 224
  train_size: 0.8
  batch_size: 32
  num_output: 26

model:
  embedding_dim: 2
  num_kernels: 3
  num_filters1: 128
  num_filters2: 64
  num_hidden: 128
  num_hidden2: 64
  pooling_dim: 2
  stride: 1
  padding: 1
  stridepool: 2
  paddingpool: 0
  
train:
    epochs: 100
    learning_rate: 0.001
    pretrain: 0
